import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./v1"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: "http://localhost:5032",
  fetch: (input) => {
    return fetch(input, {
        credentials: 'include'
    });
  },
});

export const $api = createClient(fetchClient);
